-- Generated by scripts/export_schema.py - do not edit by hand.
-- The SQLAlchemy models in libs/support_common/support_common/models.py are the
-- source of truth; re-run the script after changing them.
--
-- Applied automatically by docker-compose on first start of the postgres
-- container. For an existing database use Alembic instead:
--     alembic -c database/alembic.ini upgrade head

SET client_min_messages TO WARNING;

-- Enum types
DO $$ BEGIN
    CREATE TYPE channel AS ENUM ('slack', 'email', 'api', 'zendesk', 'web');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
    CREATE TYPE ticket_status AS ENUM ('new', 'processing', 'resolved', 'escalated', 'failed', 'reopened', 'closed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
    CREATE TYPE ticket_priority AS ENUM ('low', 'normal', 'high', 'urgent');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
    CREATE TYPE message_sender AS ENUM ('customer', 'agent', 'system', 'human');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
    CREATE TYPE escalation_reason AS ENUM ('low_confidence', 'no_kb_match', 'max_turns_exceeded', 'customer_requested', 'policy_required', 'sensitive_topic', 'llm_error');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Tables
CREATE TABLE tickets (
	id SERIAL NOT NULL, 
	ticket_id VARCHAR(32) NOT NULL, 
	subject VARCHAR(500) NOT NULL, 
	body TEXT NOT NULL, 
	customer_external_id VARCHAR(128) NOT NULL, 
	customer_email VARCHAR(320), 
	customer_name VARCHAR(200), 
	customer_tier VARCHAR(32) NOT NULL, 
	channel channel NOT NULL, 
	status ticket_status NOT NULL, 
	priority ticket_priority NOT NULL, 
	external_ref VARCHAR(256), 
	tags JSONB NOT NULL, 
	metadata JSONB NOT NULL, 
	first_response_at TIMESTAMP WITH TIME ZONE, 
	closed_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_tickets_ticket_id UNIQUE (ticket_id), 
	CONSTRAINT uq_tickets_channel_external_ref UNIQUE (channel, external_ref)
);
CREATE TABLE ticket_feedback (
	id SERIAL NOT NULL, 
	ticket_id VARCHAR(32) NOT NULL, 
	satisfaction_score INTEGER NOT NULL, 
	comment TEXT, 
	resolved_issue BOOLEAN, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_feedback_score_range CHECK (satisfaction_score BETWEEN 1 AND 5), 
	CONSTRAINT uq_feedback_ticket UNIQUE (ticket_id), 
	FOREIGN KEY(ticket_id) REFERENCES tickets (ticket_id) ON DELETE CASCADE
);
CREATE TABLE ticket_messages (
	id SERIAL NOT NULL, 
	ticket_id VARCHAR(32) NOT NULL, 
	sender message_sender NOT NULL, 
	message TEXT NOT NULL, 
	turn INTEGER, 
	metadata JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(ticket_id) REFERENCES tickets (ticket_id) ON DELETE CASCADE
);
CREATE TABLE ticket_resolutions (
	id SERIAL NOT NULL, 
	ticket_id VARCHAR(32) NOT NULL, 
	solution TEXT NOT NULL, 
	confidence FLOAT NOT NULL, 
	escalated BOOLEAN NOT NULL, 
	escalation_reason escalation_reason, 
	model VARCHAR(128) NOT NULL, 
	turns_used INTEGER NOT NULL, 
	citations JSONB NOT NULL, 
	tool_calls JSONB NOT NULL, 
	latency_ms FLOAT NOT NULL, 
	estimated_cost_usd FLOAT NOT NULL, 
	resolved_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_resolution_confidence CHECK (confidence >= 0 AND confidence <= 1), 
	FOREIGN KEY(ticket_id) REFERENCES tickets (ticket_id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX ix_tickets_channel_created_at ON tickets (channel, created_at);
CREATE INDEX ix_tickets_created_at ON tickets (created_at);
CREATE INDEX ix_tickets_customer_external_id ON tickets (customer_external_id);
CREATE INDEX ix_tickets_status ON tickets (status);
CREATE INDEX ix_tickets_status_created_at ON tickets (status, created_at);
CREATE INDEX ix_ticket_feedback_created_at ON ticket_feedback (created_at);
CREATE INDEX ix_ticket_feedback_ticket_id ON ticket_feedback (ticket_id);
CREATE INDEX ix_ticket_messages_ticket_created ON ticket_messages (ticket_id, created_at);
CREATE INDEX ix_ticket_messages_ticket_id ON ticket_messages (ticket_id);
CREATE INDEX ix_resolutions_escalated_resolved_at ON ticket_resolutions (escalated, resolved_at);
CREATE INDEX ix_ticket_resolutions_resolved_at ON ticket_resolutions (resolved_at);
CREATE INDEX ix_ticket_resolutions_ticket_id ON ticket_resolutions (ticket_id);

-- Reporting helper: the auto-resolution rate that the project targets at 65%.
CREATE OR REPLACE VIEW ticket_resolution_stats AS
SELECT
    date_trunc('day', r.resolved_at)                                   AS day,
    t.channel                                                          AS channel,
    count(*)                                                           AS decided,
    count(*) FILTER (WHERE NOT r.escalated)                            AS auto_resolved,
    round(
        count(*) FILTER (WHERE NOT r.escalated)::numeric
        / nullif(count(*), 0), 4
    )                                                                  AS auto_resolution_rate,
    round(avg(r.confidence)::numeric, 4)                               AS avg_confidence,
    round(avg(r.latency_ms)::numeric, 2)                               AS avg_latency_ms,
    round(avg(r.estimated_cost_usd)::numeric, 6)                       AS avg_cost_usd
FROM ticket_resolutions r
JOIN tickets t ON t.ticket_id = r.ticket_id
GROUP BY 1, 2;
