#!/usr/bin/env python
"""Render ``database/schema.sql`` from the SQLAlchemy models.

The ORM models are the source of truth. This script emits the equivalent DDL so
that Postgres can bootstrap itself from ``docker-entrypoint-initdb.d`` without
running Alembic, and so the schema is reviewable in a diff.

Re-run it after changing any model::

    python scripts/export_schema.py
"""

from __future__ import annotations

from pathlib import Path

from sqlalchemy import Index
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

from support_common.models import Base

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "database" / "schema.sql"

HEADER = """\
-- Generated by scripts/export_schema.py - do not edit by hand.
-- The SQLAlchemy models in libs/support_common/support_common/models.py are the
-- source of truth; re-run the script after changing them.
--
-- Applied automatically by docker-compose on first start of the postgres
-- container. For an existing database use Alembic instead:
--     alembic -c database/alembic.ini upgrade head

SET client_min_messages TO WARNING;
"""


def render() -> str:
    """Produce the full DDL: enum types, tables, then indexes."""
    dialect = postgresql.dialect()
    parts: list[str] = [HEADER]

    # Enum types must exist before the tables that reference them. SQLAlchemy
    # would emit them inline per column, which breaks when two tables share one.
    seen_enums: set[str] = set()
    parts.append("\n-- Enum types\n")
    for table in Base.metadata.sorted_tables:
        for column in table.columns:
            enum_type = getattr(column.type, "native_enum", None)
            name = getattr(column.type, "name", None)
            if enum_type and name and name not in seen_enums:
                seen_enums.add(name)
                values = ", ".join(f"'{v}'" for v in column.type.enums)
                parts.append(
                    f"DO $$ BEGIN\n"
                    f"    CREATE TYPE {name} AS ENUM ({values});\n"
                    f"EXCEPTION WHEN duplicate_object THEN NULL;\n"
                    f"END $$;\n"
                )

    parts.append("\n-- Tables\n")
    for table in Base.metadata.sorted_tables:
        statement = str(CreateTable(table).compile(dialect=dialect)).strip()
        # The enum types are created above; suppress SQLAlchemy's inline CREATE TYPE.
        parts.append(f"{statement};\n")

    parts.append("\n-- Indexes\n")
    for table in Base.metadata.sorted_tables:
        for index in sorted(table.indexes, key=lambda i: i.name or ""):
            assert isinstance(index, Index)
            parts.append(f"{str(CreateIndex(index).compile(dialect=dialect)).strip()};\n")

    parts.append(
        """
-- Reporting helper: the auto-resolution rate that the project targets at 65%.
CREATE OR REPLACE VIEW ticket_resolution_stats AS
SELECT
    date_trunc('day', r.resolved_at)                                   AS day,
    t.channel                                                          AS channel,
    count(*)                                                           AS decided,
    count(*) FILTER (WHERE NOT r.escalated)                            AS auto_resolved,
    round(
        count(*) FILTER (WHERE NOT r.escalated)::numeric
        / nullif(count(*), 0), 4
    )                                                                  AS auto_resolution_rate,
    round(avg(r.confidence)::numeric, 4)                               AS avg_confidence,
    round(avg(r.latency_ms)::numeric, 2)                               AS avg_latency_ms,
    round(avg(r.estimated_cost_usd)::numeric, 6)                       AS avg_cost_usd
FROM ticket_resolutions r
JOIN tickets t ON t.ticket_id = r.ticket_id
GROUP BY 1, 2;
"""
    )
    return "".join(parts)


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
